# Generated by Django 5.2.16 on 2026-10-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('contact', models.CharField(max_length=254)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('delivery_method', models.CharField(choices=[('ship', 'Ship'), ('pickup', 'Pickup')], max_length=10)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('billing_address', models.JSONField()),
                ('shipping_method', models.CharField(blank=True, default='', max_length=30)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery (COD)'), ('bank_deposit', 'Bank Deposit')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apps_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'apps_orderitem',
                'ordering': ['id'],
            },
        ),
    ]
