# Generated by Django 5.2.16 on 2026-10-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery (COD)'), ('bank_deposit', 'Bank Deposit'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], max_length=20),
        ),
    ]
