# Generated by Django 5.2.16 on 2026-08-09 10:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=255)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="apps.attribute",
                    ),
                ),
            ],
            options={
                "ordering": ["attribute", "value"],
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("logo", models.URLField(blank=True, default="", max_length=500)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="apps_brand_slug_5da93f_idx"),
                    models.Index(
                        fields=["is_active"], name="apps_brand_is_acti_eeb35b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("image", models.URLField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="apps_catego_slug_5009ef_idx"),
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="apps_catego_is_acti_244574_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sku", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="apps.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="apps.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sku", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="apps.product",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("threshold", models.IntegerField()),
                ("quantity_at_alert", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.IntegerField(blank=True, null=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="low_stock_alerts",
                        to="apps.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_quantity", models.IntegerField(default=0)),
                ("new_quantity", models.IntegerField(default=0)),
                ("quantity_change", models.IntegerField(default=0)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("stock_in", "Stock In"),
                            ("stock_out", "Stock Out"),
                            ("adjustment", "Adjustment"),
                            ("reservation", "Reservation"),
                            ("release", "Release"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("actor_user_id", models.IntegerField(blank=True, null=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="apps.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("reserved_quantity", models.IntegerField(default=0)),
                ("low_stock_threshold", models.IntegerField(default=10)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="apps.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecentlyViewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                (
                    "product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("thumbnail", models.CharField(blank=True, default="", max_length=500)),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-viewed_at", "-id"],
                "unique_together": {("user_id", "product_id")},
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("image", models.URLField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="apps.category",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="apps.subcategory",
            ),
        ),
        migrations.CreateModel(
            name="VariantAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_assignments",
                        to="apps.attributevalue",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="apps.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="apps.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_assignments",
                        to="apps.attributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="apps.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product"], name="apps_produc_product_b3a1f2_idx"
                    ),
                    models.Index(
                        fields=["attribute_value"],
                        name="apps_produc_attribu_57366f_idx",
                    ),
                ],
                "unique_together": {("product", "attribute_value")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField(max_length=500)),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="apps.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_primary"],
                        name="apps_produc_product_631ccc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.IntegerField(db_index=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="apps.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "status"],
                        name="apps_produc_product_cfd4f2_idx",
                    ),
                    models.Index(
                        fields=["product", "rating"],
                        name="apps_produc_product_2af273_idx",
                    ),
                    models.Index(
                        fields=["user_id"], name="apps_produc_user_id_f8aab8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=500)),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="apps.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="apps_produc_product_8b6d56_idx"
                    )
                ],
                "unique_together": {("product", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "status"], name="apps_produc_product_238b23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="apps_produc_sku_6a7501_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["barcode"], name="apps_produc_barcode_32dc36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(
                fields=["variant", "status"], name="apps_lowsto_variant_9de0f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(
                fields=["status", "created_at"], name="apps_lowsto_status_9605a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["variant", "action"], name="apps_invent_variant_a17bed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["variant", "created_at"], name="apps_invent_variant_7021de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["action", "created_at"], name="apps_invent_action_a634ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["variant"], name="apps_invent_variant_bb77c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["category", "is_active"], name="apps_subcat_categor_18600e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(fields=["slug"], name="apps_subcat_slug_b3d8be_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("category", "slug")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="apps_produc_sku_15c5e5_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="apps_produc_slug_b8a43c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "status"], name="apps_produc_brand_i_cef2a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="apps_produc_categor_e85506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["subcategory", "status"], name="apps_produc_subcate_24200c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_featured"], name="apps_produc_status_3ae91d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="apps_produc_created_3fbc80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variantattributevalue",
            index=models.Index(
                fields=["variant"], name="apps_varian_variant_99f7f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variantattributevalue",
            index=models.Index(
                fields=["attribute_value"], name="apps_varian_attribu_9b9290_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantattributevalue",
            unique_together={("variant", "attribute_value")},
        ),
        migrations.AddIndex(
            model_name="variantprice",
            index=models.Index(
                fields=["variant", "is_active"], name="apps_varian_variant_d45a3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variantprice",
            index=models.Index(
                fields=["is_active", "effective_from", "effective_to"],
                name="apps_varian_is_acti_b60fe3_idx",
            ),
        ),
    ]
