# Generated by Django 5.2.16 on 2026-08-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_outboxevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name'), ('category', 'slug')},
        ),
    ]
