# Generated by Django 5.2.16 on 2026-10-04 14:43

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=apps.payments.models.new_payment_id, editable=False, max_length=20, unique=True)),
                ('payment_method', models.CharField(choices=[('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'Easypaisa')], max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=10)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'apps_payment',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'status'], name='apps_paymen_order_i_e44d8d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('payment_method', 'provider_transaction_id'), name='payment_unique_provider_transaction'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING'])), fields=('order',), name='payment_one_active_per_order')],
            },
        ),
    ]
