# Generated by Django 5.2.16 on 2026-09-29 19:34

from django.db import migrations, models


def backfill_stats(apps, schema_editor):
    # Uses the live helper: it only touches columns added in this migration.
    from apps.catalog.stats import refresh_product_stats

    refresh_product_stats()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'price_max'], name='product_status_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'rating_avg'], name='product_status_rating_idx'),
        ),
        migrations.RunPython(backfill_stats, migrations.RunPython.noop),
    ]
